# d02的配置文件
lidar: 
  lidar_type: "avia" # rs16, ls16, tw, vanjee, airy
  use_livox_driver: 2 # 使用的livox2驱动的版本, 1 使用livox1驱动, 其他雷达设置为0使用标准的ros消息
  lidar_topic: "/livox/lidar"
  point_filter_num: 3 # 点云滤波次数
  lidar_min_range: 1.0 # 雷达最小范围
  lidar_max_range: 100 # 雷达最大范围
  lidar_position_noise_std: 0.001 # 雷达位置噪声标准差
  lidar_rotation_noise_std: 0.001 # 雷达方向噪声标准差
  is_tms_head: false # 雷达的时间戳是否为帧首
  lidar_noise_std: 0.001 # 雷达点云噪声标准差
  use_multi_lidar: 1
  lidar_left_topic: ""
  lidar_right_topic: ""
  
imu:
  imu_topic: "/livox/imu"
  imu_scale: 10 # livoximu的输出需要缩放
  acc_noise_std: 0.01 # 加速度噪声标准差
  gyro_noise_std: 0.01 # 陀螺仪噪声标准差
  acc_bias_noise_std: 0.0001 # 加速度 bias 噪声标准差
  gyro_bias_noise_std: 0.0001 # 陀螺仪 bias 噪声标准差

encoder:
  encoder_topic: /odom
  encoder_position_noise_std: 1e-3 # 编码器平移噪声标准差
  encoder_rotation_noise_std: 1e-3 # 编码器旋转噪声标准差
  wheel_cov: 1e-2 # 编码器平移噪声标准差
  nhc_y: 1e-2 # 编码器旋转噪声标准差
  nhc_z: 1e-3 # 编码器旋转噪声标准差

gnss:
  gnss_topic: /gps/fix
  gnss_position_noise_std: 1e-3 #  GNSS 位置噪声标准差
  gnss_rotation_noise_std: 1e-3 #  GNSS 方向噪声标准差
  has_orientation: false

# robot_link和encoder是重合的
# lidar->robot的外参，雷达绕y轴旋转了25°
T_lidar2robot: [1.0000000,  0.0000000,  0.0000000, 0.0000000, 
                0.0000000,  1.0000000,  0.0000000, 0.0000000, 
                0.0000000,  0.0000000,  1.0000000, 0.0000000,
                0.0000000,  0.0000000,  0.0000000, 1.0000000]
# lidar->imu的外参
T_lidar2imu: [1.0000000,  0.0000000,  0.0000000, 0.0000000, 
                0.0000000,  1.0000000,  0.0000000, 0.0000000, 
                0.0000000,  0.0000000,  1.0000000, 0.0000000,
                0.0000000,  0.0000000,  0.0000000, 1.0000000]
# imu->encoder的外参，实际在代码中完成计算
T_imu2encoder: [0.9082976,  0.0000000,  0.4183246, 0.1810,
                0.0000000,  1.0000000,  0.0000000, 0.0230,
                -0.4183246, 0.0000000,  0.9082976, 0.3230,
                0.0000000,  0.0000000,  0.0000000, 1.0000]
                
T_gnss2imu: [1.0000000, 0.0000000, 0.0000000, 0.0000000,
             0.0000000, 1.0000000, 0.0000000, 0.0000000,
             0.0000000, 0.0000000, 1.0000000, 0.0000000,
             0.0000000, 0.0000000, 0.0000000, 1.0000000]

gravity: 9.81 # 重力加速度

use_p2plane: false # 在多楼层的退化下，使用p2plane会失败，所以这里不使用
use_voxel: false
use_ndt: false # 不要用，这算法有点问题
use_fasterlio: false  # 在多楼层的退化下，使用p2plane会失败，所以这里不使用
use_superlio: true # 是否使用SuperLIO算法

has_encoder: false
has_gnss: false
has_camera: false

front_end:
  # 里程计前端的通用参数
  calib_lidar2imu: false # 是否标定外参
  keep_angle_ranges: [-180, 180] # 保留的角度范围
  remove_ranges: [0.05, -0.15, 0.2, -0.2] # [x, -x, y, -y] 前左右的正方向上
  max_iteration: 3 # 最大迭代次数
  keyframe_size: 15
  keyframe_distance: 0.5 # 关键帧距离
  keyframe_angle_distance: 0.5 # 关键帧角度 rads
  use_angle_keyframe: true  # 是否使用角度关键帧
  save_map: true # 是否保存地图
  pcd_save_interval: -1 # 保存地图的间隔 设置成 -1, 不保存单个的pcd关键帧
  map_dir: "/home/li/ros2_ws" # 地图的目录

  use_p2plane: 
    p2plane_thresh: 0.01 # 平面阈值
    downsample: 0.2 # 降采样
    map_resolution: 0.3 # 地图分辨率
    cube_len: 300 # 立方体长度
    det_range: 60 # 检测范围
    move_thresh: 1.5 # 移动阈值

  use_voxel_map: 
    voxle_size: 0.5
    max_layer: 2 #  # 4 layer, 0, 1, 2, 3
    layer_point_size: [5, 5, 5, 5, 5] # 每层开始估计平面的阈值
    plannar_threshold: 0.01 # 平面阈值
    max_points_size: 1000 # 每个voxel最大的点云数量
    max_cov_points_size: 1000 # 每个voxel最大的协方差点云数量
    max_capacity: 10000 # 整体的voxel个数
    update_omp: false # 更新voxel地图时使用omp加速
    sigma_num: 3

    pub_voxel_map: true # 发布voxel地图
    pub_max_voxel_layer: 1 # 发布层数
    pub_point_cloud: true # 发布点云
    dense_map_enable: false # 是否发布稠密地图
    pub_point_cloud_skip: 5             # publish one points per five points
    ranging_cov: 0.03 #点云范围噪声
    angle_cov: 0.1 #点云角度噪声


  use_ndt: # 增量的ndt配准算法
    voxel_size: 1.0
    near_search: true # 默认的临近搜索的6
    max_capacity: 100000
    min_effective_pts: 10
    min_pts_in_voxel: 5
    max_pts_in_voxel: 50
    res_outlier_thresh: 10
    eps: 0.001

  use_fasterlio:
    ivox_grid_resolution: 0.2        # default=0.2
    ivox_nearby_type: 6             # 6, 18, 26
    esti_plane_threshold: 0.01        # default=0.1

  use_superlio:
    ivox_resolution: 0.5        # default=0.2
    esti_plane_threshold: 0.01        # default=0.1
localizer:
    use_meta_maps: true # 使用图元地图
    global_map_filter_size: 0.3 # 对全局地图的降采样
    local_map_dir: "/home/kilox/maps/6_office" # 地图的目录
    register_method: "gicp" # "ceres", "LM" 
    point_to_plane: 0.01 # 点到平面的距离
    dist_to_robot: 50  # 图元中心到机器人的距离
    num_trans: 1
    num_rot: 1
    delta_trans: 1  # [-1, 0，1]
    delta_rot: 0.3  # [-0.3, 0, 0.3]
    init_icp_score: 0.10
    icp_dist_thresh: 1.0 # 最邻近搜索的阈值，小于1m的点都计算进来
    update_search_dist_thresh: 1.0 # 搜索的阈值，小于1m的点都计算进来
    match_score_thresh: 1.0 # 匹配的阈值，小于0.1的点都计算进来
    use_ceres: true  
