# d02的配置文件
lidar: 
  lidar_type: "mid360" # rs16, ls16, tw, vanjee, airy
  use_livox_driver: 0 # 使用的livox2驱动的版本, 1 使用livox1驱动, 其他雷达设置为0使用标准的ros消息
  lidar_nums: 1
  lidar_topics: ["/livox/lidar"]
  point_filter_num: 1 # 点云滤波次数
  lidar_min_range: 0.10 # 雷达最小范围
  lidar_max_range: 100 # 雷达最大范围
  lidar_position_noise_std: 0.01 # 雷达位置噪声标准差
  lidar_rotation_noise_std: 0.01 # 雷达方向噪声标准差
  is_tms_head: true # 雷达的时间戳是否为帧首
  lidar_noise_std: 0.001 # 雷达点云噪声标准差
  
imu:
  imu_topic: "/livox/imu"
  imu_scale: 10 # livoximu的输出需要缩放
  acc_noise_std: 0.014715 # 加速度噪声标准差
  gyro_noise_std: 0.00244 # 陀螺仪噪声标准差
  acc_bias_noise_std: 0.0559 # 加速度 bias 噪声标准差
  gyro_bias_noise_std: 0.00656 # 陀螺仪 bias 噪声标准差

encoder:
  encoder_topic: "/odom"
  encoder_position_noise_std: 1e-3 # 编码器平移噪声标准差
  encoder_rotation_noise_std: 1e-3 # 编码器旋转噪声标准差
  wheel_cov: 1e-2 # 编码器平移噪声标准差
  nhc_y: 1e-2 # 编码器旋转噪声标准差
  nhc_z: 1e-3 # 编码器旋转噪声标准差

gnss:
  gnss_topic: "/gnss"
  gnss_position_noise_std: 1e-3 #  GNSS 位置噪声标准差
  gnss_rotation_noise_std: 1e-3 #  GNSS 方向噪声标准差
  has_orientation: false

# robot_link和encoder是重合的
# lidar->robot的外参，雷达绕y轴旋转了25°
T_lidar2robot: [0.9082976,  0.0000000,  0.4183246, 0.1895, 
                0.0000000,  1.0000000,  0.0000000, 0.0000, 
                -0.4183246, 0.0000000,  0.9082976, 0.3681,
                0.0000000,  0.0000000,  0.0000000, 1.0000]
# lidar->imu的外参
T_lidar2imu: [1.000000,  0.0000000, 0.0000000, -0.01100000,
              0.0000000, 1.0000000, 0.0000000, -0.02329000,
              0.0000000, 0.0000000, 1.0000000, 0.044120000, 
              0.0000000, 0.0000000, 0.0000000, 1.0000000]
# imu->encoder的外参，实际在代码中完成计算
T_imu2encoder: [0.9082976,  0.0000000,  0.4183246, 0.1810,
                0.0000000,  1.0000000,  0.0000000, 0.0230,
                -0.4183246, 0.0000000,  0.9082976, 0.3230,
                0.0000000,  0.0000000,  0.0000000, 1.0000]

gravity: 9.81 # 重力加速度

use_p2plane: true # fastlio2的里程计算法
use_voxel: false # voxelmap的里程计算法
use_ndt: false # 不要用，这算法有点问题

has_encoder: false
has_gnss: false

front_end:
  # 里程计前端的通用参数
  calib_lidar2imu: false # 是否标定外参
  keep_angle_ranges: [-160, 160] # 保留的角度范围
  remove_ranges: [0.05, -0.15, 0.2, -0.2] # [x, -x, y, -y] 前左右的正方向上
  max_iteration: 4 # 最大迭代次数
  # 关键帧参数
  keyframe_size: 15
  keyframe_distance: 0.5 # 关键帧距离
  keyframe_angle_distance: 0.5 # 关键帧角度 rads
  use_angle_keyframe: true  # 是否使用角度关键帧

  use_p2plane: 
    p2plane_thresh: 0.01 # 平面阈值
    downsample: 0.2 # 降采样
    map_resolution: 0.3 # 地图分辨率
    cube_len: 300 # 立方体长度
    det_range: 60 # 检测范围
    move_thresh: 1.5 # 移动阈值

  use_voxel_map: 
    voxle_size: 0.5
    max_layer: 2 #  # 4 layer, 0, 1, 2, 3
    layer_point_size: [5, 5, 5, 5, 5] # 每层开始估计平面的阈值
    plannar_threshold: 0.01 # 平面阈值
    max_points_size: 1000 # 每个voxel最大的点云数量
    max_cov_points_size: 1000 # 每个voxel最大的协方差点云数量
    max_capacity: 10000 # 整体的voxel个数
    update_omp: false # 更新voxel地图时使用omp加速
    sigma_num: 3

    pub_voxel_map: true # 发布voxel地图
    pub_max_voxel_layer: 1 # 发布层数
    pub_point_cloud: true # 发布点云
    dense_map_enable: false # 是否发布稠密地图
    pub_point_cloud_skip: 5             # publish one points per five points
    ranging_cov: 0.03 #点云范围噪声
    angle_cov: 0.1 #点云角度噪声


  use_ndt: # 增量的ndt配准算法
    voxel_size: 1.0
    near_search: true # 默认的临近搜索的6
    max_capacity: 100000
    min_effective_pts: 10
    min_pts_in_voxel: 5
    max_pts_in_voxel: 50
    res_outlier_thresh: 10
    eps: 0.001

localizer:
  use_meta_maps: true # 使用图元地图
  global_map_filter_size: 0.3 # 对全局地图的降采样
  local_map_dir: "/home/kilox/maps/6_office" # 地图的目录
  register_method: "gicp" # "ceres", "LM" 
  point_to_plane: 0.01 # 点到平面的距离
  dist_to_robot: 50  # 图元中心到机器人的距离
  num_trans: 1
  num_rot: 1
  delta_trans: 1  # [-1, 0，1]
  delta_rot: 0.3  # [-0.3, 0, 0.3]
  init_icp_score: 0.10
  icp_dist_thresh: 1.0 # 最邻近搜索的阈值，小于1m的点都计算进来
  update_search_dist_thresh: 1.0 # 搜索的阈值，小于1m的点都计算进来
  match_score_thresh: 1.0 # 匹配的阈值，小于0.1的点都计算进来
  use_ceres: true





